### ISSUE TITLE
Fix: Logo Name

### ISSUE THREAD

**Issue by tymnec** [Code-Odyssey-Editor/website#14]
Spell Mistake Fix it `Odyessey` to `Odyssey`

- [x] Fix the typo

![image](https://github.com/Code-Odyssey-Editor/website/assets/84772872/470eae84-8eec-4a85-97fb-165b2584646d)

Additional Change the Logo:

- [x] Requirement logo should be in `svg` format.
- [x] No Merge Conflicts

**Comment by Tashuuuu** [comment]
I would like to work on it.
