### ISSUE TITLE
Add Dynamic Background Effect in Hero Page (Main Page)

### ISSUE THREAD

**Issue by tymnec** [Code-Odyssey-Editor/website#23]
Using framer motion adds a background particle dynamic effects.
You are free to do anything creative design. (But different for both dark and light modes).

**Comment by tymnec** [comment]
@Cheemagagan give your review on this: 
![image](https://github.com/Code-Odyssey-Editor/website/assets/84772872/232c0cb4-ecf3-40a8-af47-93c60bd464ae)

**Comment by Cheemagagan** [comment]
Great!
