### ISSUE TITLE
Complete Editor Page View

### ISSUE THREAD

**Issue by tymnec** [Code-Odyssey-Editor/website#36]
@Cheemagagan Please mention all sub tasks here as a todo list:

**Comment by Cheemagagan** [comment]
Left bottom -Done!

<img width="1364" alt="image" src="https://github.com/Code-Odyssey-Editor/website/assets/149753323/a4a5fb85-ca07-454c-8280-b229c65ce5f2">

**Comment by KanishqxMehta** [comment]
Project explorer interface done
<img width="1470" alt="image" src="https://github.com/Code-Odyssey-Editor/website/assets/132186237/e5a2e391-d3d6-45a7-9aaf-a18dfeeb5ece">

**Comment by Cheemagagan** [comment]
Adding some feature in the left bottom side like setting icon, user icon
<img width="71" alt="image" src="https://github.com/Code-Odyssey-Editor/website/assets/149753323/376e4e22-f35f-4681-b698-a429f5da1eaf">

**Comment by KanishqxMehta** [comment]
Folder Panel ready!

![image](https://github.com/Code-Odyssey-Editor/website/assets/132186237/ca5bb98f-02f9-4029-9136-c819ba2e8c49)

**Comment by Cheemagagan** [comment]
Header Done 

<img width="1392" alt="image" src="https://github.com/Code-Odyssey-Editor/website/assets/149753323/1a51ef3c-aa83-4fe9-89d9-2bb4cde58e60">

**Comment by Cheemagagan** [comment]
Maximize view:
![image](https://github.com/Code-Odyssey-Editor/website/assets/149753323/8030e717-c603-489d-941a-2920bfa29b14)

Minimize view:
![image](https://github.com/Code-Odyssey-Editor/website/assets/149753323/68cc0fa1-571f-42a4-9bbe-314215c59450)

**Comment by KanishqxMehta** [comment]
Maximizedview:

<img width="1470" alt="image" src="https://github.com/Code-Odyssey-Editor/website/assets/132186237/7a3f173c-d73f-435e-a35a-1d638794ac4f">

Minimized View: 
<img width="496" alt="image" src="https://github.com/Code-Odyssey-Editor/website/assets/132186237/4beaa80f-39fc-4bcf-a9f6-be029f600884">

**Comment by KanishqxMehta** [comment]
<img width="1470" alt="image" src="https://github.com/Code-Odyssey-Editor/website/assets/132186237/30419408-0d43-4f60-a1c7-e77a3322f761">

**Comment by Cheemagagan** [comment]
Updated Bottom right Corner:-
<img width="387" alt="image" src="https://github.com/Code-Odyssey-Editor/website/assets/149753323/67c7fd53-4522-4bc1-a361-ab7c443ca697">

**Comment by KanishqxMehta** [comment]
Implementation of monaco editor
<img width="1470" alt="image" src="https://github.com/Code-Odyssey-Editor/website/assets/132186237/1178fd90-2f75-466a-b217-a13533b4001e">

**Comment by KanishqxMehta** [comment]
It's working well but the appearence is not correct for code input

<img width="1469" alt="image" src="https://github.com/Code-Odyssey-Editor/website/assets/132186237/d67833a8-4867-4615-86bb-ff75aefc1f4e">

**Comment by tymnec** [comment]
@KanishqxMehta @Cheemagagan this isn't responsive a lot of work to do here: 
![image](https://github.com/Code-Odyssey-Editor/website/assets/84772872/4cc1c452-51ca-4d95-b24d-98910507048b)

**Comment by tymnec** [comment]
will do in upcoming days

**Comment by Cheemagagan** [comment]
Animated Background 
<img width="1470" alt="image" src="https://github.com/Code-Odyssey-Editor/website/assets/149753323/c26a76bc-918d-49e4-b09e-1aa3b331650d">


https://github.com/Code-Odyssey-Editor/website/assets/149753323/5b638a4f-f499-4a66-a801-3f6d0b781f31
