### ISSUE TITLE
Fix: Typo mistake

### ISSUE THREAD

**Issue by tymnec** [Code-Odyssey-Editor/website#43]
fix the typo from: contact -> Contact

![image](https://github.com/Code-Odyssey-Editor/website/assets/84772872/7eb82821-c5a7-4f66-b5dd-96ff77079426)

Changes to be made here:
`/src/components/footer/footer.tsx`

`line 10:  name: "contact", `

**Comment by KanishqxMehta** [comment]
Typo Mistake Fixed

<img width="315" alt="image" src="https://github.com/Code-Odyssey-Editor/website/assets/132186237/d238139f-9e61-422c-abf0-29a4202ea113">
