### ISSUE TITLE
Create contact page

### ISSUE THREAD

**Issue by tymnec** [Code-Odyssey-Editor/website#45]
Add a new page - **Contact page** - that should support both light and dark modes.

- [x] No merge conflicts
- [x] Support dark mode

**Comment by Cheemagagan** [comment]
Shall you please tell me which type of field I can add on it @tymnec

**Comment by tymnec** [comment]
link this: 
![image](https://github.com/Code-Odyssey-Editor/website/assets/84772872/cf953c83-28b4-44f1-a114-0a8575135bff)
